### PR TITLE
Download data

### PR DESCRIPTION
**Pull request by ritisha2000**

### CODE REVIEW

**Review by brabbit61 — DISMISSED** [review]
import os
- Import the above library

os.path.join(opt["--file_path"] , "drug_consumption.csv")
- Replace the file path in the to_csv() function with the above line because to make it OS agnostic. The backslash won't work on my Ubuntu system.

**Comment by shaunhutch** [comment]
Agreed, the backslash is not necessary here. But the download works for me

**Comment by brabbit61** [comment]
Yep, it might be because you're using Windows. It won't work for Ubuntu and Mac(?)

**Comment by ritisha2000** [comment]
Thanks for the correction

**Comment by shaunhutch** [comment]
Now that this is corrected, do you want to test this Jenit? As it was working for me

**Comment by brabbit61** [comment]
You're not assigning the path to any variable.

Please replace the lines:
os.path.join(opt["--file_path"] , "drug_consumption.csv")
    data.to_csv(opt["--file_path"], index = False)

With the following:
filepath = os.path.join(opt["--file_path"] , "drug_consumption.data")
 data.to_csv(filepath, index = False)

**Comment by brabbit61** [comment]
def main(opt):
    data = pd.read_csv(opt["--url"], header=None)
    filepath = os.path.join(opt["--file_path"] , "drug_consumption.csv")
    data.to_csv(filepath, index = False)

**Review by shaunhutch — APPROVED** [review]
Changes have been made

**Pull request merged**
